version: '3'
services:
  espial:
    image: 'jonschoning/espial:espial'
    # ports:
    #   - "3000:3000"
    volumes:
      - '.:/app/data'
    network_mode: host
    environment:
      - PORT=80
      - IP_FROM_HEADER=true
      - SQLITE_DATABASE=/app/data/espial.sqlite3
      # - SSL_ONLY=false
      # - DETAILED_LOGGING=false
      # - SHOULD_LOG_ALL=false
      # - ARCHIVE_SOCKS_PROXY_HOST=localhost 
      # - ARCHIVE_SOCKS_PROXY_PORT=8888
      # - SOURCE_CODE_URI=https://github.com/jonschoning/espial
