version: '3'
services:
  espial:
    image: 'jonschoning/espial:espial'
    ports:
      - "3000:3000"
    volumes:
      - '.:/app/data'
    environment:
      - IP_FROM_HEADER=true
      - SQLITE_DATABASE=/app/data/espial.sqlite3
      - ekg_datadir=ekg
