version: '3'
services:
  espial:
    image: 'jonschoning/espial:espial'
    ports:
      - "3000:3000"
    volumes:
      - '.:/app/data'
    network_mode: host
    environment:
      - IP_FROM_HEADER=true
      - SQLITE_DATABASE=/app/data/espial.sqlite3
      # - DETAILED_LOGGING=true
      # - SHOULD_LOG_ALL=true
      # - ARCHIVE_SOCKS_PROXY_HOST=localhost 
      # - ARCHIVE_SOCKS_PROXY_PORT=8888
      # - SOURCE_CODE_URI=https://github.com/jonschoning/espial
